var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',4);
subject.inc('',4);
subject.inc('',undefined);
subject.inc(-10,undefined);
subject.inc(10,undefined);
subject.inc(10,undefined);
subject.weird(7,'','','');
subject.weird(597,'','','');
subject.weird(597,-11,'','');
subject.weird(597,1,'','');
subject.weird(597,1,36,'');
subject.weird(597,1,1542,'');
subject.weird(597,1,1542,'');
subject.weird("strict--350");
subject.weird(597,1,1542,"strict");
subject.weird("strict--625");
subject.weird(597,1,1542,"strict");
subject.weird(597,1,1542,"strict");
subject.weird(597,1,1542,"strict");
mock({"path/fileExists":{"file1":"a.txt"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"a.txt"},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"a.txt"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.format('','',{"normalize" : true});
subject.format('1-197-483-6971 x6743','',{"normalize" : true});
subject.blackListNumber('192-626-6702');
subject.blackListNumber("212-985-895");
subject.blackListNumber('192-626-6702');
