var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',2);
subject.inc('',2);
subject.inc('',undefined);
subject.inc(-6,undefined);
subject.inc(5,undefined);
subject.inc(5,undefined);
subject.weird(-2,'','','');
subject.weird(300,'','','');
subject.weird(300,-3,'','');
subject.weird(300,5,'','');
subject.weird(300,5,34,'');
subject.weird(300,5,602,'');
subject.weird(300,5,602,'');
subject.weird("strict--006");
subject.weird(300,5,602,"strict");
subject.weird("strict--180");
subject.weird(300,5,602,"strict");
subject.weird(300,5,602,"strict");
subject.weird(300,5,602,"strict");
mock({"path/fileExists":{"file1":"a.txt"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"a.txt"},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"a.txt"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.format('','',{"normalize" : true});
subject.format('014.574.9046 x161','',{"normalize" : true});
subject.blackListNumber('1-620-638-0795 x205');
subject.blackListNumber("212-755-665");
subject.blackListNumber('1-620-638-0795 x205');
