var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',3);
subject.inc('',20);
subject.inc('',undefined);
subject.inc(-7,undefined);
subject.inc(9,undefined);
subject.inc(9,undefined);
subject.weird(7,'','','');
subject.weird(436,'','','');
subject.weird(436,-10,'','');
subject.weird(436,1,'','');
subject.weird(436,1,32,'');
subject.weird(436,1,1397,'');
subject.weird(436,1,1397,"strict18");
subject.weird(436,1,1397,"strict");
subject.weird(436,1,1397,15);
subject.weird(436,1,1397,"strict");
subject.weird(436,1,1397,"strict");
mock({"path/fileExists":{"file1":"a.txt"},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"a.txt"},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{"file1":"a.txt"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.format('','',{"normalize" : true});
subject.format('377-579-7097 x4365','',{"normalize" : true});
subject.blackListNumber('536-625-7907 x12322');
subject.blackListNumber("212-689-239");
subject.blackListNumber('536-625-7907 x12322');
